version: "{build}"

image: Visual Studio 2019

# init:
#     - git config --global core.autocrlf input

clone_folder: c:\projects\sprint_timer
shallow_clone: true              # only last commit without history

matrix:
    fast_finish: false           # don't stop on error in some build

platform:
    - x64

configuration:
    - Debug
    - Release

# environment:
#     matrix:
#         - TOOLCHAIN: msvc15

# install:
#     - call ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%

build: off

before_build:
    - set QTDIR=C:\Qt\5.13\msvc2017_64

build_script:
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_VERBOSE_MAKEFILE="OFF" -DCMAKE_PREFIX_PATH="C:/Qt/5.13/msvc2017_64/lib/cmake" -DCMAKE_INCLUDE_PATH="C:\Libraries\boost_1_71_0" -DBUILD_TESTS=ON -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX="C:/sprint_timer_bin"
    - mkdir C:\projects\sprint_timer\bin
    - mkdir C:\projects\sprint_timer\bin\Release
    - mkdir C:\projects\sprint_timer\bin\Debug
    - copy %QTDIR%\bin\Qt5Core.dll c:\projects\sprint_timer\bin\Release
    - copy %QTDIR%\bin\Qt5Cored.dll c:\projects\sprint_timer\bin\Debug
    - copy %QTDIR%\bin\Qt5Gui.dll c:\projects\sprint_timer\bin\Release
    - copy %QTDIR%\bin\Qt5Guid.dll c:\projects\sprint_timer\bin\Debug
    - copy %QTDIR%\bin\Qt5Multimedia.dll c:\projects\sprint_timer\bin\Release
    - copy %QTDIR%\bin\Qt5Multimediad.dll c:\projects\sprint_timer\bin\Debug
    - copy %QTDIR%\bin\Qt5Network.dll c:\projects\sprint_timer\bin\Release
    - copy %QTDIR%\bin\Qt5Networkd.dll c:\projects\sprint_timer\bin\Debug
    - copy %QTDIR%\bin\Qt5Sql.dll c:\projects\sprint_timer\bin\Release
    - copy %QTDIR%\bin\Qt5Sqld.dll c:\projects\sprint_timer\bin\Debug
    - copy %QTDIR%\bin\Qt5Widgets.dll c:\projects\sprint_timer\bin\Release
    - copy %QTDIR%\bin\Qt5Widgetsd.dll c:\projects\sprint_timer\bin\Debug
    - cmake --build . --config %configuration%

test_script:
    - ctest

# artifacts:
#     - path: <local-package-path>
#       name: package_name
#
# deploy:
#     # publish tagged commits on GitHub Releases:
#     description: '$(APPVEYOR_REPO_TAG_NAME)'
#     provider: GitHub
#
#     auth_token:
#         secure: <encrypted-github-token>
#
#     artifact: package_name
#     force_update: true
#
#     on:
#         appveyor_repo_tag: true
