version: "{build}"

image: Visual Studio 2017

# init:
#     - git config --global core.autocrlf input

clone_folder: c:\projects\sprint_timer
shallow_clone: true              # only last commit without history

matrix:
    fast_finish: false           # don't stop on error in some build

platform:
    - x64

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc15

install:
    - call ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%

build: off

build_script:
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 15 Win64" -DCMAKE_VERBOSE_MAKEFILE="OFF" -DCMAKE_PREFIX_PATH="C:/Qt/5.11.1/msvc_2017_64/lib/cmake" -DCMAKE_INCLUDE_PATH="C:\Libraries\boost_1_67_0" -DBUILD_TESTS=ON -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE
    - cmake --build . --config Release # TODO

test_script:
    - ctest

# artifacts:
#     - path: <local-package-path>
#       name: package_name
#
# deploy:
#     # выкладываем tagged-коммиты на GitHub Releases:
#     description: '$(APPVEYOR_REPO_TAG_NAME)'
#     provider: GitHub
#
#     auth_token:
#         secure: <encrypted-github-token>
#
#     artifact: package_name
#     force_update: true
#
#     on:
#         appveyor_repo_tag: true
